source 'http://rubygems.org'
source :gemcutter
gem 'addressable'
gem 'bcrypt-ruby'
gem 'bundle'
gem 'bundler'
gem 'data_mapper'
gem 'data_objects'
gem 'datamapper'
gem 'dm-aggregates'
gem 'dm-constraints'
gem 'dm-core'
gem 'dm-do-adapter'
gem 'dm-migrations'
gem 'dm-serializer'
gem 'dm-postgres-adapter'
gem 'dm-timestamps'
gem 'dm-transactions'
gem 'dm-types'
gem 'dm-validations'
gem 'fastercsv'
gem 'haml'
gem 'i18n'
gem 'json'
gem 'mail'
gem 'mime-types'
gem 'oauth'
gem 'polyglot'
gem 'pony'
gem 'rack'
gem 'rack-openid'
gem 'rake'
gem 'ruby-openid'
gem 'ruby-openid-apps-discovery'
gem 'sinatra'
gem 'stringex'
gem 'tilt'
gem 'treetop'
gem 'uuidtools'

gem "pg"
group :development do
  gem 'do_sqlite3'
  gem 'dm-sqlite-adapter'
end

